project:
  type: website
  output-dir: docs

website:
  title: "slides"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmadland
      - icon: bluesky
        href: https://bsky.app
format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: true

# References
bibliography: refs.bib
csl: apa.csl



