---
title: "Script"
format:
  docx:
    toc: true
---


## Slide 1-6

My Interest in Physiotherapy sprouted from playing football and rugby throughout high school. Since grade 8 I have suffered 3 concussions, a cracked meniscus, and a sprained ACL. Through my constant battle with rehabilitation and maintaining a healthy body, I decided to learn more about my injuries and the affected areas, to better my knowledge on how to recover faster and how to prevent long term damage. Specifically my concussions. My whole grade 9 year I had Post Concussion Syndrome, which essentially means that I struggled with migraines, brian fog, lack of concentration, fatigue, etc. for the whole year. As I struggled everyday with my symptoms, I wanted to find ways to calm my symptoms as I was tired of living in constant pain. Throughout grade 9 and 10, school was a very difficult challenge because everything triggered a migraine. The lights in the hallways, projector screens, the noise in the halls etc. In my first semester of grade 12, I took our schools Human Kinetics course to further my education on the human body and from there I made the decision to go into physiotherapy, with a specific focus on athletes recovering from sports related injury as I have a similar testimony. Sports remain a passion of mine as I leave high school athletics, which also contributes to my desire to stay connected with the sports world. I plan to volunteer my time to help coach the football team this spring as well as shadow the team trainer. During my time on the football team I had the honour of being one of four team captains, and won the “Grandpa Gore” Award. The award is named after a team volunteer who showed up, rain or shine, to show his constant support to the team. I was given this award due to my determination, my unwavering faith in my teammates and their abilities, and my leadership role on the team.

## Slide 7-8

The core competency I have chosen is Critical Thinking. As I mentioned before, I have battled with concussions throughout my whole high school journey. Throughout high school, critical thinking was actually quite a challenge due to my head injuries. I am proud to say that I was able to overcome my symptoms of PCS and now thrive in my ability to think through and process challenges that come my way, whether they be academic, or life challenges. Math and Science were a very big challenge for me in grade 9 and the first half of grade 10, I had very poor grades in math and science 9, and a very poor grade in science 10. However the turn around for me was math 10 and onward, scoring an A in the remainder of my classes excluding 1. Although my Critical Thinking skills are not as developed as other peoples, I chose this core competency because I am proud of the work I put in to improve my abilities and raise my personal ceiling to be higher than I thought possible after dealing with the head injuries that I did.

## Slide 9-11

Throughout my life I have excelled in athletics and music. I pride myself in my musical ability as a drummer. I have been drumming since I was 4. My brother had a drum kit in our basement and I did everything he did, so naturally I picked up the drums at a young age. My parents also tell me I have had an impeccable sense of timing since I was young, so they are not surprised in my success as a musician. Music has always been a passion of mine and I have even dipped my toes in the realm of making my own music, I have also been fortunate enough to be offered to track drums with producers. As I transition to University in the lower mainland, I plan to get connected with and work with a number of artists. I already connect on a regular basis with a drummer, asking questions about his playing style, how he has established himself on social media and the ways he uses that platform to expand his brand, and picking up tips from him in order to better my ability as an independent musician.

## Slide 11-13

The Job of a Physiotherapist is to prepare and execute a treatment plan designed to improve their patients physical ability, ease patients pains, and prevent physical problems, whether it be a reoccurring problem or a new one. Due to the complexity and unique circumstance of each individual patient, there is no “quick fix” or universal band-aid that you can slap on every patient. Every patients needs are determined by what muscle, joint, tendon, or ligament is affected. The fix for a pulled biceps brachii won’t be the same as plantar fasciitis (Micro tears on the bottom face of the foot). Physiotherapists must have a deep knowledge of how each joint and muscle movement in order to help diagnose and treat a patient when they walk into their practice. For example; If a patient walks in with shoulder pain, From there I need to determine if it is an injury to the teres major/minor, the anterior, lateral, or posterior deltoids. I can come to a diagnosis by process of elimination. If there is no pain when they raise their arm above their head, I can rule out the Anterior deltoid (front head of the delt). If they can raise their arm from their side without pain, I can rule out the Lateral Deltoid (Middle Head). If they experience pain when they bring their hand from out in front of them to their chest, I can determine it to be an injury within the muscles of the rotator cuff, so on and so forth.

## Slide 14

Physiotherapists work in a large variety of spaces with different working conditions. As a physiotherapist you can find yourself working in a public clinic, a private practice, hospitals, or in the case of specifically Rural areas, you can find yourself travelling to your patients location. From a general point of view, Physiotherapists are in an office space that is a hybrid between offices for paperwork, and a gym space with dumbbells, kettlebells, squat racks, treadmills, stationary bikes, etc. for the use of patients rehabilitation.

## Slide 15

Provincial Salaries:
- British Columbia – $114,420 per year (31% higher than national average)
- Alberta – $90,005 per year (same as national average)
- Saskatchewan – $93,213 per year (6% higher than national average)
- Manitoba – $73,825 per year (16$ below national average)
- Ontario – $86,628 per year (same as national average)
- Quebec – $84,088 per year (same as national average)
- P.E.I – $50,574 per year (42% below national average)
- Newfoundland and Labrador – 99,373 (13% above national average)
- Nova Scotia – $69,160 (21% below national average)
Source: Indeed

## Slide 16

Future outlook:
According to the government of Canada job bank, the
average provincial need is moderate. With higher demand being
in the Maritimes, and Alberta.

## Slide 17

To pursue a career in physiotherapy, you must have the following:

1. A masters degree in physiotherapy along with a period of supervised practical training.  
2. A license or registration with a regulatory body.  
3. Completion of physiotherapy competency.  

## Slide 18
I plan to take Human kinetics at Trinity Western University, and after receiving my bachelors degree I will continue my studies to pursue a masters degree in physiotherapy.

## Slide 19

My Interest in physiotherapy came from being an athlete and walking through my own injuries. My passion comes from a desire to help people on their recovery journey. Additionally, being an athlete that has struggled with injury I understand that the recovery journey is just as much mental as it is physical. Through my concussions and knee injuries, my biggest struggle was my battle with depression and anxiety. I found purpose and worth in my athletic ability and the feeling of not being good enough, or that you aren’t doing enough is paralyzing. My hope as a physiotherapists is to be able to walk with my patients in the mental recovery as well, whether that be as little as making them feel seen and understood in their circumstance, or recommending a counselor, my dream is to help people in every capacity that I am capable of.

## Slide 20

- Budget Overview

## Slide 21-

Overview and Working Conditions: 

Carpentry as a whole hold a wide variety of individual trades. You can pursue Framing, Cabinetry, furniture making, personalized trades such as specialty products like custom doors, countertops, flooring, etc. Carpentry is a physically demanding job, especially in framing. You need to be skilled with handtools and power tools, be know how to read a tape measure, and know how to work with others. Job sites vary as you are outside. You could be working in the sunshine one day, and in the cold rain the next day. Especially in a place like Canada, where the spring looks like sunshine one day and snow the next. It is load, requires heavy lifting, and due to the use of dangerous tools and heavy objects protective gear is required.

## Slide 22

The beauty of this being my plan B is the amount of entry level jobs. If my plan A were to fall through, I would be able to get my foot in the door of the trades no problem. Some private companies allow you to climb the ladder with no schooling. If this is not the case, Okanagan College supplies many great courses and apprenticeships that will go a long way to building a future in the trades.

## Slide 23

This is my backup plan due to a few reasons. First, I love working with my hands. I grew up working on projects with my Grandpa in his shop, we built a bunk bed, a desk, and too many cutting boards to count. If I don’t end up working my dream job, I want to do something that I still love to do. If I am able to still do something that I call a passion I will be less envious of the life I “could have had”. Next, It is easy to start. If I start working straight out of high school and do not have to pay for schooling, with an entry level salary I will make $77,838 in my first year according to Indeed. Finally, flexibility. Hours will vary just like any other job, but I know from good friends with similar passions to mine that they still have more than enough time as a carpenter to pursue music. My friend in Vancouver is a red seal carpenter that tracks drums for small artists on the side and is in a band.

## Slide 24

- WEX